const defaultSessions=[
 {id:1,day:0,type:'Rest day',title:'Rest & mobility',description:'20 min mobility flow, optional easy walk.',distance:0,duration:20,intensity:1},
 {id:2,day:1,type:'Easy run',title:'Easy aerobic run',description:'Conversational effort. Finish with 4 × 20 sec relaxed strides.',distance:8,duration:48,intensity:3},
 {id:3,day:2,type:'Intervals',title:'Threshold intervals',description:'3 × 10 min at threshold pace, with 2 min easy jog recovery.',distance:12,duration:68,intensity:7},
 {id:4,day:3,type:'Recovery',title:'Recovery jog',description:'Keep it light and loose. Stop early if you need to.',distance:6,duration:38,intensity:2},
 {id:5,day:4,type:'Easy run',title:'Easy + strides',description:'Easy aerobic running, then 6 × 15 sec strides with full recovery.',distance:9,duration:52,intensity:3},
 {id:6,day:5,type:'Long run',title:'Long run',description:'Easy first 18 km, then 6 km at steady marathon effort. Practice fueling.',distance:24,duration:142,intensity:5},
 {id:7,day:6,type:'Rest day',title:'Full rest',description:'Put your feet up. Prepare for the week ahead.',distance:0,duration:0,intensity:0}
];
let sessions=JSON.parse(localStorage.getItem('strideplan-sessions')||'null')||defaultSessions;let selectedId=null;
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];const dates=[2,3,4,5,6,7,8];
const typeClass=t=>({"Easy run":"easy",Intervals:'intervals',Tempo:'tempo',"Long run":'long',Recovery:'recovery',"Rest day":'rest'})[t]||'easy';
const save=()=>localStorage.setItem('strideplan-sessions',JSON.stringify(sessions));
function renderPlan(){const totalKm=sessions.reduce((a,s)=>a+s.distance,0),totalMin=sessions.reduce((a,s)=>a+s.duration,0),load=sessions.reduce((a,s)=>a+s.duration*s.intensity,0),runs=sessions.filter(s=>s.distance>0).length;document.querySelector('#weekSummary').innerHTML=[['DISTANCE',totalKm.toFixed(1)+' km'],['TIME',Math.floor(totalMin/60)+'h '+totalMin%60+'m'],['TRAINING LOAD',load],['SESSIONS',runs+' runs']].map(x=>`<div class="summary-item"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join('');document.querySelector('#weekGrid').innerHTML=days.map((day,i)=>{const todays=sessions.filter(s=>s.day===i);return `<article class="day ${i===2?'today':''}"><div class="day-head"><span class="day-name">${day}</span><span class="day-date">${dates[i]}</span></div>${todays.length?todays.map(s=>`<div class="session ${typeClass(s.type)}" data-id="${s.id}" tabindex="0"><span class="session-type">${s.type}</span><h3>${s.title}</h3><span class="session-meta">${s.distance?s.distance+' km · ':''}${s.duration?s.duration+' min':''}</span></div>`).join(''):'<p class="empty-day">No session planned</p>'}<button class="add-mini" data-day="${i}" aria-label="Add session on ${day}">+</button></article>`}).join('');const next=sessions.find(s=>s.day>=2&&s.distance>0)||sessions.find(s=>s.distance>0);document.querySelector('#upNextTitle').textContent=next.title;document.querySelector('#upNextDetails').innerHTML=`<div><b>${next.distance} km</b>total distance</div><div><b>${next.duration} min</b>estimated time</div><div><b>${next.intensity} / 10</b>expected intensity</div><div><b>${next.description.split('.')[0]}</b>workout focus</div>`;document.querySelectorAll('.session').forEach(el=>{el.onclick=()=>openSession(+el.dataset.id);el.onkeydown=e=>{if(e.key==='Enter')openSession(+el.dataset.id)}});document.querySelectorAll('.add-mini').forEach(el=>el.onclick=()=>openSession(null,+el.dataset.day));}
function openSession(id,day=0){const s=id?sessions.find(x=>x.id===id):{id:'',day,type:'Easy run',title:'',description:'',distance:5,duration:30,intensity:4};selectedId=id;sessionId.value=s.id;modalDay.textContent=id?'EDIT SESSION':`ADD SESSION · ${days[day].toUpperCase()}`;modalTitle.textContent=id?s.title:'New training session';editTitle.value=s.title;editType.value=s.type;editDescription.value=s.description;editDistance.value=s.distance;editDuration.value=s.duration;editIntensity.value=s.intensity;intensityOutput.value=s.intensity;sessionDialog.showModal()}
function showToast(message){toast.textContent=message;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600)}
sessionForm.addEventListener('submit',e=>{e.preventDefault();const existing=sessions.find(s=>s.id===selectedId);const item={id:selectedId||Date.now(),day:existing?.day??0,type:editType.value,title:editTitle.value,description:editDescription.value,distance:+editDistance.value,duration:+editDuration.value,intensity:+editIntensity.value};if(existing)Object.assign(existing,item);else sessions.push(item);save();renderPlan();sessionDialog.close();showToast(selectedId?'Session updated':'Session added to your week')});
editIntensity.oninput=()=>intensityOutput.value=editIntensity.value;deleteSession.onclick=()=>{if(!selectedId)return; sessions=sessions.filter(s=>s.id!==selectedId);save();renderPlan();sessionDialog.close();showToast('Session deleted')};
addSession.onclick=()=>openSession(null,0);openNext.onclick=()=>openSession(sessions.find(s=>s.day>=2&&s.distance>0)?.id);todayBtn.onclick=()=>document.querySelector('.today').scrollIntoView({behavior:'smooth',block:'center'});prevWeek.onclick=nextWeek.onclick=()=>showToast('This is a draft week view — edits are saved locally.');
document.querySelectorAll('.nav-link').forEach(link=>link.onclick=e=>{e.preventDefault();document.querySelectorAll('.nav-link').forEach(x=>x.classList.remove('active'));link.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.classList.remove('active-view'));document.querySelector('#'+link.dataset.view).classList.add('active-view');window.scrollTo({top:0,behavior:'smooth'})});
themeToggle.onclick=()=>document.body.classList.toggle('dark');
const weekly=[32,39,43,47,51,38,54,58,61,64,56,68],loads=[160,178,195,210,232,154,238,256,284,303,245,315];function renderInsights(){const sum=sessions.reduce((a,s)=>a+s.duration*s.intensity,0);metricGrid.innerHTML=[['THIS WEEK',sessions.reduce((a,s)=>a+s.distance,0).toFixed(1)+' km','+8% from last week'],['TIME ON FEET',sessions.reduce((a,s)=>a+s.duration,0)+' min','steady aerobic work'],['TRAINING LOAD',sum,'well-balanced effort'],['LONGEST RUN','24 km','Saturday long run']].map(x=>`<div class="metric"><span class="metric-label">${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></div>`).join('');distanceChart.innerHTML=weekly.map((v,i)=>`<div class="bar-group"><div class="bar" style="height:${v/70*100}%"><span>${v}</span></div><label>W${i+1}</label></div>`).join('');loadTotal.textContent='315 load';const pts=loads.map((v,i)=>`${i/(loads.length-1)*600+10},${170-v/350*145}`).join(' ');loadChart.innerHTML=`<defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#0c6a57" stop-opacity=".22"/><stop offset="1" stop-color="#0c6a57" stop-opacity="0"/></linearGradient></defs><path d="M10,190 L${pts} L610,190 Z" fill="url(#fill)"/><polyline points="${pts}" fill="none" stroke="#0c6a57" stroke-width="3" stroke-linejoin="round"/>${loads.map((v,i)=>`<circle cx="${i/(loads.length-1)*600+10}" cy="${170-v/350*145}" r="4" fill="#0c6a57"/>`).join('')}`}
builderForm.addEventListener('submit',e=>{e.preventDefault();const d=raceDistance.value,time=goalTime.value,date=new Date(raceDate.value+'T12:00').toLocaleDateString('en-US',{month:'long',day:'numeric',year:'numeric'});generatedPlan.hidden=false;generatedPlan.innerHTML=`<p class="eyebrow">DRAFT CREATED</p><h2>${d} plan for ${time}</h2><p>Your personalized 16-week plan peaks in time for ${date}. It includes 4 phases, 64 editable sessions, and a progressive long-run schedule.</p><button class="button primary" id="viewDraft">View draft week →</button>`;generatedPlan.scrollIntoView({behavior:'smooth'});document.querySelector('#viewDraft').onclick=()=>document.querySelector('[data-view=plan]').click()});exportBtn.onclick=()=>showToast('Export prepared — your plan data is saved in this browser.');
renderPlan();renderInsights();
